### ISSUE TITLE
Missing documentation about activating LexikTranslationBundle

### ISSUE THREAD

**Issue by nurikabe** [tamago-db/TamagoTipsManagerBundle#1]
I think we need to mention that this has to be activited in AppKernel.

**Comment by blodberg** [comment]
You mean to register Lexik bundle?

**Comment by nurikabe** [comment]
Right.  It needs to be specified in the AppKernel, otherwise there will be a crash.

**Comment by blodberg** [comment]
I added it in the Readme file!

**Comment by sanskritijain29** [comment]
Fixed all the 'todo's' mentioned in the readme. Closing this issue.
