### ISSUE TITLE
Crash if we try to retrieve tip for a locale that has not yet been defined

### ISSUE THREAD

**Issue by nurikabe** [tamago-db/TamagoTipsManagerBundle#12]
Trying to retrieve a tip for the "ja" locale crashes.  Need to use Lexik's fallback feature I think.

**Comment by blodberg** [comment]
So we can just ask the user to define a fallback locale in the config file right? I assumed it will use the default locale as fallback.

**Comment by nurikabe** [comment]
Ideally we would define a reasonable default in our bundle and provide the user with instructions on how to override.  If it's not possible to define a default, then instructions on how to configure Lexik for this should be fine.

**Comment by nurikabe** [comment]
Let's go ahead and just add documentation to the README.  We need to do this anyway I think.  Users of our bundle will need to configure at least the following in their config:

```
lexik_translation:
    fallback_locale: [ <locale> ]
    managed_locales: [ <locale1>, <local2>, ... ]
```

Those already using the LexikTranslationBundle should already have these defined.
