### ISSUE TITLE
Domain is hardcoded

### ISSUE THREAD

**Issue by nurikabe** [tamago-db/TamagoTipsManagerBundle#14]
Notice in the controller that we are doing this:

`$transUnits = $repositoryTransUnit->findByDomain('tips-general');`

`tips-general` is hardcoded.  Let's make this configurable in the render, for example:

`{{ render(controller('TamagoTipsManagerBundle:TipsManager:index', {'domain': 'some-domain-name'})) }}`

In this way users of our library can split tips into multiple categories.

**Comment by nurikabe** [comment]
Be sure to update the README when done.

**Comment by sanskritijain29** [comment]
Added a fix. Please check if it looks good.
README updated.

**Comment by nurikabe** [comment]
Looks good!
