### ISSUE TITLE
Why does the end user have to define the management route?

### ISSUE THREAD

**Issue by nurikabe** [tamago-db/TamagoTipsManagerBundle#4]
The README tell the user to define a route for the Lexik management screen:

https://github.com/tamago-db/TamagoTipsManagerBundle#routing

Ideally, since we are building on top of Lexik, we should do this for them.  Define a route like `_tips-manager`.

Note the use of a preceding underscore.  This is a defacto standard which implies an internal/admin-only route.

**Comment by nurikabe** [comment]
Looks like we updated the documentation about the translation manager route, but my point here is that we don't need to put this in the `README` at all.  We should be able to set this for the user inside `TamagoTipsManagerBundle`.

**Comment by nurikabe** [comment]
Be sure to use a more intuitive route than `/lexik/grid`.  Most end users won't be aware of the details of the LexikTranslationBundle.

**Comment by sanskritijain29** [comment]
Please see the fix.

**Comment by nurikabe** [comment]
Looks good.  Thanks.
