### ISSUE TITLE
Create one example tip in it's own domain inside TamagoTipsManagerBundle

### ISSUE THREAD

**Issue by nurikabe** [tamago-db/TamagoTipsManagerBundle#5]
Details here:  http://symfony.com/doc/current/book/translation.html

Have at least one sample tip in it's own domain will ensure that Lexik loads that domain into it's grid:

![image](https://cloud.githubusercontent.com/assets/83678/13080823/5e2e2856-d498-11e5-9723-f03a15f027fa.png)

**Comment by sanskritijain29** [comment]
We have a domain 'TamagoTipsManager' which shows up in Lexik grid:

![image](https://cloud.githubusercontent.com/assets/15094839/13127774/53570f30-d59f-11e5-98fc-9a23862079f2.png)

Does this make sense?

**Comment by nurikabe** [comment]
How is this configured?

**Comment by nurikabe** [comment]
Ping

**Comment by sanskritijain29** [comment]
I added it manually in one of the lexik tables while creating the first dummy tip.

**Comment by nurikabe** [comment]
Thanks.  How will users of the bundle be able to configure this?  Is there any way to configure automatically?

**Comment by blodberg** [comment]
Not yet. By default it doesn't show any domain 
![screenshot from 2016-02-24 23 46 25](https://cloud.githubusercontent.com/assets/10999733/13310084/fff817c8-db50-11e5-8ac1-5e82e823360a.png)

**Comment by sanskritijain29** [comment]
It won't show up on your end. I added it manually in my local.

**Comment by nurikabe** [comment]
Understood.  The point is that there should be a way for us to configure in the bundle such that end users don't have to configure manually.

**Comment by nurikabe** [comment]
I think what we need to do is advice users to do something like this:

https://github.com/lexik/LexikTranslationBundle/blob/master/Resources/doc/index.md#import-translations

I believe we did this when we were initially playing around with Lexik?

Note that there is a `bundleName` option.  So what we could do is create some example tips and then in the README advice users to import the tips for just our TamagoTipsManagerBundle into the database.

**Comment by blodberg** [comment]
I think we will have to create our own command for that.

**Comment by nurikabe** [comment]
I'm 95% sure we can do this with the existing Lexik command..

**Comment by blodberg** [comment]
Yes. We got this done in the last meeting! I updated the Readme too

**Comment by blodberg** [comment]
https://github.com/tamago-db/TamagoTipsManagerBundle#import-translations

**Comment by nurikabe** [comment]
See clarifications in README
