### ISSUE TITLE
Ajax script in main application twig

### ISSUE THREAD

**Issue by sanskritijain29** [tamago-db/TamagoTipsManagerBundle#8]
Last time, we moved the below chunk from our tip twig to the symfony demo home page twig:

![image](https://cloud.githubusercontent.com/assets/15094839/13512625/d1a86b56-e169-11e5-8082-f9148464d23e.png)

Do we have to ask the user to add this script in their application via the README? Is it okay to ask them to do so?

**Comment by nurikabe** [comment]
Yes, I think so.
